import { boolean, integer, pgTable, serial, text } from 'drizzle-orm/pg-core';

export const seasons = pgTable('seasons', {
  id: serial('id').primaryKey(),
  default: boolean('default').notNull(),
  name: text('name').notNull(),
  logo: text('logo').notNull(),
  description: text('description').notNull(),
  mathcesplayed: integer('played').notNull().default(0),
  wins: integer('wins').notNull().default(0),
  points: integer('points').notNull().default(0),
  robot3D: text('robotmodelurl'),
  book: text('book'),
  robotdesc: text('robotdesc').notNull(),
  meetstitle: text('meetstitle').array(),
  meets: text('meets').array().notNull(),
  meetPosts: text('mPosts').array(),
  meetImage: text('mimgs').array(),
  demostitle: text('demostitle').array(),
  demos: text('demos').array().notNull(),
  demosPosts: text('dposts').array(),
  demoImage: text('dimg').array(),
  regionals: text('regionals').notNull(),
  regionalPost: text('rPost'),
  regionalImage: text('rimg'),
  nationals: text('nationals').notNull(),
  nationalPost: text('nPost'),
  nationalImage: text('nimg'),
  internationals: text('internationals'),
  internationalPost: text('iPost'),
  internationalImage: text('iimg'),
  awards: text('awards').array(),
  awardsdesc: text('awardsdesc').array(),
  bgColor: text('bgcolor').notNull(),
  mainColor: text('maincolor').notNull(),
  accentColor: text('acColor').notNull(),
  published: boolean('published').notNull().default(false)
});
